BOARDS = {
    "esp32_s2": {
        "display": {
            "spi_id": 2,
            "sck": 36,
            "mosi": 35,
            "miso": None,
            "cs": 5,
            "dc": 6,
            "rst":None,
            "blk": 8,
            "rotation": 0,
            "baudrate": 20000000,
        },
        "cc1101": {
            "spi_id": 1,
            "sck": 7,
            "mosi": 11,
            "miso": 9,
            "cs": 16,
            "gdo0": 4,
            "gdo2": 13,
        },
        "led": 15,
    },

    "esp32_s3": {
        "display": {
            "spi_id": 1,
            "sck": 7,
            "mosi": 6,
            "miso": None,
            "cs": 14,
            "dc": 15,
            "rst": 21,
            "blk": 22,
            "rotation": 3,
        },
        "cc1101": {
            "spi_id": 0,
            "sck": 17,
            "mosi": 2,
            "miso": 3,
            "cs": 16,
            "gdo0": 20,
            "gdo2": 9,
        },
        "led": 15,
    },

    "esp32_c6": {
        "display": {
            "spi_id": 1,
            "sck": 7,
            "mosi": 6,
            "miso": None,
            "cs": 14,
            "dc": 15,
            "rst": 21,
            "blk": 22,
            "rotation": 3,
        },
        "cc1101": {
            "spi_id": 1,
            "sck": 17,
            "mosi": 2,
            "miso": 3,
            "cs": 16,
            "gdo0": 20,
            "gdo2": 9,
        },
        "led": 15,
    },
}